### ISSUE TITLE
Retorno de JSON com erro nos caracteres especiais

### ISSUE THREAD

**Issue by isacmoura** [hudsonbrendon/py-correios#1]
O JSON retornado após passar um código de rastreio está vindo com alguns erros nos caracteres especiais. Tentei explicitar o enconding utf-8 no arquivo que estava utilizando, mas o erro persistiu. Irei analisar o código e tentar achar a solução.

**Comment by hudsonbrendon** [comment]
Fique a vontade, mas acredito que isso seja parte do retorno da API que estou usando.
